In [2]:
from pathlib import Path
import pandas as pd

# Use Path to build Windows-safe paths and avoid backslash-escape issues
base = Path(r"C:\Users\LENOVO\Desktop\Kavi docu\jobs\f1-business-analytics")

races = pd.read_csv(base / "data" / "raw" / "races.csv")
drivers = pd.read_csv(base / "data" / "raw" / "drivers.csv")
constructors = pd.read_csv(base / "data" / "raw" / "constructors.csv")
results = pd.read_csv(base / "data" / "raw" / "results.csv")
pit_stops = pd.read_csv(base / "data" / "raw" / "pit_stops.csv")

print(races.shape, drivers.shape, constructors.shape, results.shape, pit_stops.shape)

(1149, 18) (864, 9) (212, 5) (27238, 18) (12192, 7)

In [3]:
races.info()
races.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149 entries, 0 to 1148
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1149 non-null   int64
 1   year         1149 non-null   int64
 2   round        1149 non-null   int64
 3   circuitId    1149 non-null   int64
 4   name         1149 non-null   object
 5   date         1149 non-null   object
 6   time         1149 non-null   object
 7   url          1149 non-null   object
 8   fp1_date     1125 non-null   object
 9   fp1_time     1125 non-null   object
 10  fp2_date     1125 non-null   object
 11  fp2_time     1125 non-null   object
 12  fp3_date     1125 non-null   object
 13  fp3_time     1125 non-null   object
 14  quali_date   1125 non-null   object
 15  quali_time   1125 non-null   object
 16  sprint_date  1125 non-null   object
 17  sprint_time  1125 non-null   object
dtypes: int64(4), object(14)
memory usage: 161.7+ KB

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [4]:
results.info()
results.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27238 entries, 0 to 27237
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         27238 non-null  int64
 1   raceId           27238 non-null  int64
 2   driverId         27238 non-null  int64
 3   constructorId    27238 non-null  int64
 4   number           27238 non-null  object
 5   grid             27238 non-null  object
 6   position         27238 non-null  object
 7   positionText     27238 non-null  object
 8   positionOrder    27238 non-null  int64
 9   points           27238 non-null  float64
 10  laps             27238 non-null  int64
 11  time             27238 non-null  object
 12  milliseconds     27238 non-null  object
 13  fastestLap       27238 non-null  object
 14  rank             27238 non-null  object
 15  fastestLapTime   27238 non-null  object
 16  fastestLapSpeed  27238 non-null  object
 17  statusId         27238 non-null  int64
dtypes: float64(1), int64(7), object(10)
memory usage: 3.7+ MB

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.3,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [5]:
drivers.info()
drivers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     864 non-null    int64
 1   driverRef    864 non-null    object
 2   number       864 non-null    object
 3   code         864 non-null    object
 4   forename     864 non-null    object
 5   surname      864 non-null    object
 6   dob          864 non-null    object
 7   nationality  864 non-null    object
 8   url          864 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.9+ KB

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [6]:
constructors.info()
constructors.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    object
 2   name            212 non-null    object
 3   nationality     212 non-null    object
 4   url             212 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.4+ KB

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [7]:
pit_stops.info()
pit_stops.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12192 entries, 0 to 12191
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        12192 non-null  int64
 1   driverId      12192 non-null  int64
 2   stop          12192 non-null  int64
 3   lap           12192 non-null  int64
 4   time          12192 non-null  object
 5   duration      12192 non-null  object
 6   milliseconds  12192 non-null  int64
dtypes: int64(5), object(2)
memory usage: 666.9+ KB

   raceId  driverId  stop  lap      time duration  milliseconds
0     841       153     1    1  17:05:23   26.898         26898
1     841        30     1    1  17:05:52   25.021         25021
2     841        17     1   11  17:20:48   23.426         23426
3     841         4     1   12  17:22:34   23.251         23251
4     841        13     1   13  17:24:10   23.842         23842

In [8]:
def inspect_df(df, name):
    print(f"\n{name}")
    print("-"*40)
    print(df.info())
    print("\nNull values:\n", df.isnull().sum())
    print("\nDuplicates:", df.duplicated().sum())

inspect_df(races, "RACES")
inspect_df(drivers, "DRIVERS")
inspect_df(constructors, "CONSTRUCTORS")
inspect_df(results, "RESULTS")
inspect_df(pit_stops, "PIT STOPS")

RACES
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149 entries, 0 to 1148
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1149 non-null   int64
 1   year         1149 non-null   int64
 2   round        1149 non-null   int64
 3   circuitId    1149 non-null   int64
 4   name         1149 non-null   object
 5   date         1149 non-null   object
 6   time         1149 non-null   object
 7   url          1149 non-null   object
 8   fp1_date     1125 non-null   object
 9   fp1_time     1125 non-null   object
 10  fp2_date     1125 non-null   object
 11  fp2_time     1125 non-null   object
 12  fp3_date     1125 non-null   object
 13  fp3_time     1125 non-null   object
 14  quali_date   1125 non-null   object
 15  quali_time   1125 non-null   object
 16  sprint_date  1125 non-null   object
 17  sprint_time  1125 non-null   object
dtypes: int64(4), object(14)
memory usage: 161.7+ KB
None

Null values:
 raceId          0
year            0
round           0
circuitId       0
name            0
date            0
time            0
url             0
fp1_date       24
fp1_time       24
fp2_date       24
fp2_time       24
fp3_date       24
fp3_time       24
quali_date     24
quali_time     24
sprint_date    24
sprint_time    24
dtype: int64

Duplicates: 0

DRIVERS
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     864 non-null    int64
 1   driverRef    864 non-null    object
 2   number       864 non-null    object
 3   code         864 non-null    object
 4   forename     864 non-null    object
 5   surname      864 non-null    object
 6   dob          864 non-null    object
 7   nationality  864 non-null    object
 8   url          864 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.9+ KB
None

Null values:
 driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

Duplicates: 0

CONSTRUCTORS
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    object
 2   name            212 non-null    object
 3   nationality     212 non-null    object
 4   url             212 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.4+ KB
None

Null values:
 constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

Duplicates: 0

RESULTS
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27238 entries, 0 to 27237
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         27238 non-null  int64
 1   raceId           27238 non-null  int64
 2   driverId         27238 non-null  int64
 3   constructorId    27238 non-null  int64
 4   number           27238 non-null  object
 5   grid             27238 non-null  object
 6   position         27238 non-null  object
 7   positionText     27238 non-null  object
 8   positionOrder    27238 non-null  int64
 9   points           27238 non-null  float64
 10  laps             27238 non-null  int64
 11  time             27238 non-null  object
 12  milliseconds     27238 non-null  object
 13  fastestLap       27238 non-null  object
 14  rank             27238 non-null  object
 15  fastestLapTime   27238 non-null  object
 16  fastestLapSpeed  27238 non-null  object
 17  statusId         27238 non-null  int64
dtypes: float64(1), int64(7), object(10)
memory usage: 3.7+ MB
None

Null values:
 resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

Duplicates: 0

PIT STOPS
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12192 entries, 0 to 12191
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        12192 non-null  int64
 1   driverId      12192 non-null  int64
 2   stop          12192 non-null  int64
 3   lap           12192 non-null  int64
 4   time          12192 non-null  object
 5   duration      12192 non-null  object
 6   milliseconds  12192 non-null  int64
dtypes: int64(5), object(2)
memory usage: 666.9+ KB
None

Null values:
 raceId          0
driverId        0
stop            0
lap             0
time            0
duration        0
milliseconds    0
dtype: int64

Duplicates: 0

In [9]:
races.drop_duplicates(inplace=True)
drivers.drop_duplicates(inplace=True)
constructors.drop_duplicates(inplace=True)
results.drop_duplicates(inplace=True)
pit_stops.drop_duplicates(inplace=True)

In [10]:
races.isnull().sum()
drivers.isnull().sum()
constructors.isnull().sum() 
results.isnull().sum()
pit_stops.isnull().sum()

raceId          0
driverId        0
stop            0
lap             0
time            0
duration        0
milliseconds    0
dtype: int64

In [11]:
drivers['nationality'].fillna('Unknown', inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12904\4181352775.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  drivers['nationality'].fillna('Unknown', inplace=True)

In [12]:
constructors['nationality'].fillna('Unknown', inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12904\3072001726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  constructors['nationality'].fillna('Unknown', inplace=True)

In [13]:
results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [14]:
results['points'].fillna(0, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12904\3507185794.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['points'].fillna(0, inplace=True)

In [15]:
results['dnf'] = results['position'].isnull().astype(int)

In [16]:
results['position'].fillna(0, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12904\3253157637.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['position'].fillna(0, inplace=True)

In [17]:
races['date'] = pd.to_datetime(races['date'])

In [18]:
num_cols = ['grid', 'position', 'points', 'laps']
results[num_cols] = results[num_cols].apply(pd.to_numeric)

ValueError: Unable to parse string "\N" at position 27198

In [20]:
import numpy as np

results.replace("\\N", np.nan, inplace=True)

In [21]:
num_cols = ['grid', 'position', 'points', 'laps']

results[num_cols] = results[num_cols].apply(
    pd.to_numeric, errors='coerce'
)

In [22]:
results['points'].fillna(0, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12904\3507185794.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['points'].fillna(0, inplace=True)

In [23]:
results['dnf'] = results['position'].isna().astype(int)
results['position'].fillna(0, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12904\272187476.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['position'].fillna(0, inplace=True)

In [24]:
results[num_cols].isnull().sum()
results[num_cols].dtypes

grid        float64
position    float64
points      float64
laps          int64
dtype: object

In [25]:
for df_ in [races, drivers, constructors, results]:
    df_.replace("\\N", np.nan, inplace=True)

In [26]:

results.describe()

,resultId,raceId,driverId,constructorId,grid,position,positionOrder,points,laps,statusId,dnf
count,27238.000000,27238.000000,27238.000000,27238.000000,27218.000000,27238.000000,27238.000000,27238.000000,27238.000000,27238.000000,27238.000000
mean,13620.548131,562.323482,287.189037,50.916807,11.123742,4.838534,12.753359,2.041672,46.457926,17.053124,0.402122
std,7864.483958,320.515332,289.313608,62.430841,7.181365,5.480000,7.642542,4.434966,29.342136,25.986529,0.490335
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,6810.250000,304.000000,59.000000,6.000000,5.000000,0.000000,6.000000,0.000000,23.000000,1.000000,0.000000
50%,13619.500000,539.000000,173.000000,25.000000,11.000000,3.000000,12.000000,0.000000,53.000000,10.000000,0.000000
75%,20431.750000,824.000000,427.000000,63.000000,17.000000,9.000000,18.000000,2.000000,66.000000,14.000000,1.000000
max,27243.000000,1168.000000,865.000000,215.000000,34.000000,33.000000,39.000000,50.000000,200.000000,141.000000,1.000000

In [27]:
results = results[results['laps'] >= 0]
results = results[results['grid'] >= 0]

In [28]:
df = results.merge(races, on='raceId', how='left')
df = df.merge(drivers, on='driverId', how='left')
df = df.merge(constructors, on='constructorId', how='left')

In [29]:
inspect_df(df, "FINAL DATASET")
df.head()

FINAL DATASET
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27218 entries, 0 to 27217
Data columns (total 48 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         27218 non-null  int64
 1   raceId           27218 non-null  int64
 2   driverId         27218 non-null  int64
 3   constructorId    27218 non-null  int64
 4   number_x         27212 non-null  object
 5   grid             27218 non-null  float64
 6   position         27218 non-null  float64
 7   positionText     27218 non-null  object
 8   positionOrder    27218 non-null  int64
 9   points           27218 non-null  float64
 10  laps             27218 non-null  int64
 11  time_x           8008 non-null   object
 12  milliseconds     8008 non-null   object
 13  fastestLap       8689 non-null   object
 14  rank             8947 non-null   object
 15  fastestLapTime   8689 non-null   object
 16  fastestLapSpeed  8252 non-null   object
 17  statusId         27218 non-null  int64
 18  dnf              27218 non-null  int32
 19  year             27218 non-null  int64
 20  round            27218 non-null  int64
 21  circuitId        27218 non-null  int64
 22  name_x           27218 non-null  object
 23  date             27218 non-null  datetime64[ns]
 24  time_y           8749 non-null   object
 25  url_x            27218 non-null  object
 26  fp1_date         1799 non-null   object
 27  fp1_time         1359 non-null   object
 28  fp2_date         1799 non-null   object
 29  fp2_time         1359 non-null   object
 30  fp3_date         1439 non-null   object
 31  fp3_time         1059 non-null   object
 32  quali_date       1799 non-null   object
 33  quali_time       1359 non-null   object
 34  sprint_date      360 non-null    object
 35  sprint_time      300 non-null    object
 36  driverRef        27218 non-null  object
 37  number_y         7020 non-null   object
 38  code             10637 non-null  object
 39  forename         27218 non-null  object
 40  surname          27218 non-null  object
 41  dob              27218 non-null  object
 42  nationality_x    27218 non-null  object
 43  url_y            27218 non-null  object
 44  constructorRef   27218 non-null  object
 45  name_y           27218 non-null  object
 46  nationality_y    27218 non-null  object
 47  url              27218 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(1), int64(10), object(33)
memory usage: 9.9+ MB
None

Null values:
 resultId               0
raceId                 0
driverId               0
constructorId          0
number_x               6
grid                   0
position               0
positionText           0
positionOrder          0
points                 0
laps                   0
time_x             19210
milliseconds       19210
fastestLap         18529
rank               18271
fastestLapTime     18529
fastestLapSpeed    18966
statusId               0
dnf                    0
year                   0
round                  0
circuitId              0
name_x                 0
date                   0
time_y             18469
url_x                  0
fp1_date           25419
fp1_time           25859
fp2_date           25419
fp2_time           25859
fp3_date           25779
fp3_time           26159
quali_date         25419
quali_time         25859
sprint_date        26858
sprint_time        26918
driverRef              0
number_y           20198
code               16581
forename               0
surname                0
dob                    0
nationality_x          0
url_y                  0
constructorRef         0
name_y                 0
nationality_y          0
url                    0
dtype: int64

Duplicates: 0

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,code,forename,surname,dob,nationality_x,url_y,constructorRef,name_y,nationality_y,url
0,1,18,1,1,22,1.0,1.0,1,1,10.0,...,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,18,2,2,3,5.0,2.0,2,2,8.0,...,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,18,3,3,7,7.0,3.0,3,3,6.0,...,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,18,4,4,5,11.0,4.0,4,4,5.0,...,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,18,5,1,23,3.0,5.0,5,5,4.0,...,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren

In [30]:
df['driver_name'] = df['forename'] + ' ' + df['surname']
df['season'] = df['year']
df['grid_vs_finish'] = df['grid'] - df['position']

In [32]:
df.to_csv("../data/processed/f1_clean_analytics_dataset.csv", index=False)